kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: zjivAQm4ZHGV+z3WXbmupt9q+G8gmYyD+o7VaPGl0Pc=
      - identity: {}
